# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GuoJikun.QuickLook
PackageVersion: 0.24.0
InstallerLocale: zh-CN
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: quicklook
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- Publisher: jikun
  ProductCode: quicklook
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\quicklook'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GuoJikun/quicklook/releases/download/v0.24.0/quicklook_0.24.0_x64-setup.exe
  InstallerSha256: E6B56BD97028E0373D9883B59A7C81DCB80D4D0526607B06F4BB6E0051F64351
- Architecture: arm64
  InstallerUrl: https://github.com/GuoJikun/quicklook/releases/download/v0.24.0/quicklook_0.24.0_arm64-setup.exe
  InstallerSha256: 9F9FD68001A9C7C675B75C1DEFF7F24F129081C194F023FEA03A1E01A811AA7F
ManifestType: installer
ManifestVersion: 1.12.0
